export const projects = [
    {
        title: 'Stats of the day',
        description: 'Stats & Predictions for upcoming football matches.',
        tags: ['Next.js', 'TypeScript', 'Tailwind', 'RapidAPI'],
        github: '',
        link: 'https://statsoftheday.vercel.app/',
        displayLink: 'statsoftheday.com',
        id: 0,
        projectImage:'/images/projects/sotd.png'

    },
    {
        title: 'ScreenSweet',
        description: 'A list of useful UX / Design books.',
        tags: ['Astro', 'TypeScript', 'Tailwind CSS', 'GSAP'],
        github: '',
        link: 'https://www.screensweet.com/',
        displayLink: 'Screen Sweet',
        id: 2,
        projectImage:'/images/projects/screensweet.png'
    },
    {
        title: 'Yum',
        description: 'Simple recipes generated by Chat GPT.',
        tags: ['Astro', 'Tailwind', 'GSAP'],
        github: '',
        link: 'https://yum-liard.vercel.app/',
        displayLink: 'Yum',
        id: 4,
        projectImage:'/images/projects/yum.png'

    },
]